apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tic-tac-cluster
  region: us-east-1

nodeGroups:
  - name: ng-small
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: false