apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tic-tac-cluster
  region: us-east-1
  version: "1.32"

nodeGroups:
  - name: ng-small
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2