apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tic-tac-toe-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: digicashpro.com
    http:
      paths: 
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tic-tac-toe-service
              port:
                number: 80